//! `docs/srp-vectors.json`, checked against this crate's copy of the signed
//! bytes.
//!
//! [`super::identity`] and `apps/relay/src/auth.rs` carry the same four
//! functions in two crates that cannot depend on one another — `apps/server` is
//! a binary with no library to link against, and it must stay that way, because
//! the relay must never become mandatory (R6). Nothing in either build makes
//! them agree, and drift does not fail a compile: it surfaces at runtime as
//! `auth_failed`, which is also what a genuine attack, an expired nonce and a
//! refused binding all look like.
//!
//! So the enforcement is this file plus its two counterparts —
//! `apps/relay/tests/vectors.rs` and `apps/client/test/srp_vectors_test.dart`
//! — all reading the same vectors.
//!
//! This side checks **signature production**, not verification. The origin
//! server signs and never verifies these messages, so verifying here would test
//! `ed25519-dalek` rather than Storm. Ed25519 is deterministic, so a seeded
//! identity must reproduce the vector's signature byte for byte — which pins
//! the message, the key handling and the base64url-no-pad encoding in one
//! assertion, against signatures generated by an unrelated RFC 8032
//! implementation (`tools/srp-vectors/`).

use std::path::PathBuf;

use serde_json::Value;

use super::identity::{
    ServerIdentity, challenge_message, relay_auth_message, validate_nonce, validate_server_id,
};

/// The seed `docs/srp-vectors.json` was generated from. Public by design: it
/// signs test messages and nothing else.
const SEED: [u8; 32] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31,
];

/// The vectors live at the repo root, not in the crate — three implementations
/// read the one file, and a copy per crate is exactly the drift being guarded
/// against.
fn vectors() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/srp-vectors.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("srp-vectors.json is not valid JSON")
}

fn cases<'a>(doc: &'a Value, section: &str) -> &'a Vec<Value> {
    doc[section]
        .as_array()
        .unwrap_or_else(|| panic!("section `{section}` missing from srp-vectors.json"))
}

fn s<'a>(case: &'a Value, field: &str) -> &'a str {
    case[field]
        .as_str()
        .unwrap_or_else(|| panic!("field `{field}` missing from vector {case}"))
}

/// The one positive vector in a `verify_*` section — the case whose signature a
/// correct signer must reproduce exactly.
fn only_valid<'a>(doc: &'a Value, section: &str) -> &'a Value {
    let mut valid = cases(doc, section)
        .iter()
        .filter(|c| c["verifies"].as_bool() == Some(true));
    let first = valid
        .next()
        .unwrap_or_else(|| panic!("`{section}` has no positive vector"));
    assert!(
        valid.next().is_none(),
        "`{section}` has more than one positive vector; this test would silently \
         check only the first"
    );
    first
}

#[test]
fn the_file_is_the_version_this_test_understands() {
    // A v2 file read by a v1 test would pass vacuously on whichever sections it
    // still happens to recognise.
    assert_eq!(vectors()["version"].as_u64(), Some(1));
}

#[test]
fn the_domain_prefixes_are_the_ones_this_crate_uses() {
    let doc = vectors();
    let relay = s(&doc["domains"], "relay_auth");
    let challenge = s(&doc["domains"], "client_challenge");
    assert_ne!(relay, challenge, "domain separation is the whole point");
    assert!(relay_auth_message("s", "n").starts_with(relay.as_bytes()));
    assert!(challenge_message("s", "n").starts_with(challenge.as_bytes()));
    // Neither may be a prefix of the other, or a signature over the longer
    // domain could be read as one over the shorter.
    assert!(!relay.starts_with(challenge) && !challenge.starts_with(relay));
}

#[test]
fn every_relay_auth_message_vector_matches_byte_for_byte() {
    let doc = vectors();
    let list = cases(&doc, "relay_auth_message");
    assert!(
        !list.is_empty(),
        "no vectors — the file would pass vacuously"
    );
    for case in list {
        let name = s(case, "name");
        assert_eq!(
            relay_auth_message(s(case, "server_id"), s(case, "nonce")),
            s(case, "message_utf8").as_bytes(),
            "relay_auth_message vector `{name}` disagrees with this crate"
        );
    }
}

#[test]
fn every_client_challenge_message_vector_matches_byte_for_byte() {
    let doc = vectors();
    let list = cases(&doc, "client_challenge_message");
    assert!(
        !list.is_empty(),
        "no vectors — the file would pass vacuously"
    );
    for case in list {
        let name = s(case, "name");
        assert_eq!(
            challenge_message(s(case, "server_id"), s(case, "nonce")),
            s(case, "message_utf8").as_bytes(),
            "client_challenge_message vector `{name}` disagrees with this crate"
        );
    }
}

#[test]
fn the_documented_delimiter_collision_still_exists_and_is_refused() {
    // Decision 60. The collision is not a curiosity — it is the reason both
    // fields are validated, and if a framing change ever removed it this
    // section would be describing a hazard it had silently outlived.
    let doc = vectors();
    let pairs = doc["delimiter_confusion"]["colliding_pairs"]
        .as_array()
        .expect("delimiter_confusion.colliding_pairs missing");
    assert!(!pairs.is_empty());
    for pair in pairs {
        let (a, b) = (&pair["a"], &pair["b"]);
        let ma = relay_auth_message(s(a, "server_id"), s(a, "nonce"));
        assert_eq!(
            ma,
            relay_auth_message(s(b, "server_id"), s(b, "nonce")),
            "the pair no longer collides"
        );
        assert_eq!(ma, s(pair, "shared_message_utf8").as_bytes());

        for side in [a, b] {
            let accepted = validate_server_id(s(side, "server_id")).is_ok()
                && validate_nonce(s(side, "nonce")).is_ok();
            assert!(
                !accepted,
                "a colliding pair passed validation — one signature would cover \
                 two different (server_id, nonce) readings"
            );
        }
    }
}

#[test]
fn every_nonce_vector_gets_the_verdict_the_file_records() {
    let doc = vectors();
    for case in cases(&doc, "validate_nonce") {
        let name = s(case, "name");
        let expected = case["valid"].as_bool().expect("`valid` must be a bool");
        assert_eq!(
            validate_nonce(s(case, "nonce")).is_ok(),
            expected,
            "validate_nonce vector `{name}`: expected valid={expected}"
        );
    }
}

#[test]
fn every_server_id_vector_gets_the_verdict_the_file_records() {
    let doc = vectors();
    for case in cases(&doc, "validate_server_id") {
        let name = s(case, "name");
        let expected = case["valid"].as_bool().expect("`valid` must be a bool");
        assert_eq!(
            validate_server_id(s(case, "server_id")).is_ok(),
            expected,
            "validate_server_id vector `{name}`: expected valid={expected}"
        );
    }
}

#[test]
fn the_seeded_identity_is_the_key_the_vectors_were_generated_from() {
    // If this fails, every signature assertion below fails for an uninteresting
    // reason, so it is worth asserting separately.
    let doc = vectors();
    let identity = ServerIdentity::from_seed("srv_unused", SEED);
    assert_eq!(
        identity.public_key_b64(),
        s(&doc["keys"], "test_public_key_b64")
    );
}

#[test]
fn sign_relay_auth_reproduces_the_vector_signature_exactly() {
    let doc = vectors();
    let case = only_valid(&doc, "verify_relay_auth");
    let identity = ServerIdentity::from_seed(s(case, "server_id"), SEED);
    assert_eq!(
        identity.public_key_b64(),
        s(case, "public_key_b64"),
        "the vector was signed with a different key"
    );
    assert_eq!(
        identity
            .sign_relay_auth(s(case, "nonce"))
            .expect("the vector's nonce must be valid"),
        s(case, "signature_b64"),
        "sign_relay_auth no longer produces the bytes a relay will verify"
    );
}

#[test]
fn sign_challenge_reproduces_the_vector_signature_exactly() {
    let doc = vectors();
    let case = only_valid(&doc, "verify_client_challenge");
    let identity = ServerIdentity::from_seed(s(case, "server_id"), SEED);
    assert_eq!(identity.public_key_b64(), s(case, "public_key_b64"));
    assert_eq!(
        identity.sign_challenge(s(case, "nonce")),
        s(case, "signature_b64"),
        "sign_challenge no longer produces the bytes the client will verify"
    );
}

#[test]
fn the_two_domains_never_produce_the_same_signature() {
    // The property the prefixes exist for, asserted on real signatures rather
    // than inferred from the message builders: one signature must never prove
    // both "I may register at this relay" and "I am your server".
    let doc = vectors();
    let relay = only_valid(&doc, "verify_relay_auth");
    let challenge = only_valid(&doc, "verify_client_challenge");
    assert_eq!(
        s(relay, "server_id"),
        s(challenge, "server_id"),
        "the two positive vectors must share a server_id for this to mean anything"
    );
    assert_eq!(s(relay, "nonce"), s(challenge, "nonce"));
    assert_ne!(s(relay, "signature_b64"), s(challenge, "signature_b64"));
}

#[test]
fn sign_relay_auth_refuses_every_field_the_vectors_call_invalid() {
    // `sign_relay_auth` validates both fields itself rather than trusting its
    // caller, so the refusals are part of the signing contract and not only of
    // the validators.
    let doc = vectors();
    let good_nonce = s(only_valid(&doc, "verify_relay_auth"), "nonce");

    for case in cases(&doc, "validate_server_id") {
        if case["valid"].as_bool() == Some(false) {
            let identity = ServerIdentity::from_seed(s(case, "server_id"), SEED);
            assert!(
                identity.sign_relay_auth(good_nonce).is_err(),
                "signed for an invalid server_id (`{}`)",
                s(case, "name")
            );
        }
    }

    let identity = ServerIdentity::from_seed("srv_valid", SEED);
    for case in cases(&doc, "validate_nonce") {
        if case["valid"].as_bool() == Some(false) {
            assert!(
                identity.sign_relay_auth(s(case, "nonce")).is_err(),
                "signed an invalid nonce (`{}`)",
                s(case, "name")
            );
        }
    }
}
