#!/usr/bin/env python3
"""Generate docs/runtime-vectors.json (PLAN.md decision 77b).

Run from the repo root. The file is a wire commitment between apps/server and
apps/runtime, which cannot depend on each other: a changed vector is a protocol
change and belongs in PLAN.md, not in a quiet regeneration.

Uses the reference Ed25519 that tools/srp-vectors already ships, so the
expected bytes come from an implementation unrelated to either crate.
"""

import base64
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "srp-vectors"))
import ed25519_ref as ed  # noqa: E402

HOST_AUTH_PREFIX = "storm-host-auth:v1:"
ENROLL_PREFIX = "storm-enroll:v1:"


def b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")


def token_id(token: str) -> str:
    # `sen_<id>.<secret>` -> `hen_<id>`: the public half names the enrollment.
    assert token.startswith("sen_")
    public, _secret = token[len("sen_"):].split(".", 1)
    return "hen_" + public


def enroll_msg(server_id: str, tid: str) -> bytes:
    return f"{HOST_AUTH_PREFIX}{server_id}:{tid}".encode()


def connect_msg(server_id: str, host_id: str, nonce: str) -> bytes:
    return f"{HOST_AUTH_PREFIX}{server_id}:{host_id}:{nonce}".encode()


# Fixed seeds: the private keys here are worthless by construction.
HOST_SEED = bytes(range(32, 64))
HOST_PK = ed.publickey(HOST_SEED)
SERVER_SEED = bytes(range(32))
SERVER_PK = ed.publickey(SERVER_SEED)

SERVER_ID = "srv_01ARZ3NDEKTSV4RRFFQ69G5FAV"
HOST_ID = "hst_01HB6V3Z7Q2M4N8P0R5S9T1W3X"
NONCE = "Qm9vbXRvd25Ob25jZTEyMzQ1Njc4"
TOKEN = "sen_01HB6V3Z7Q2M4N8P0R5S9T1W3Y." + b64(bytes(range(100, 132)))

TID = token_id(TOKEN)
EM = enroll_msg(SERVER_ID, TID)
CM = connect_msg(SERVER_ID, HOST_ID, NONCE)

URL = "http://192.168.1.51:8484"
ENROLLMENT = f"{ENROLL_PREFIX}{URL}:{SERVER_ID}:{b64(SERVER_PK)}:{TOKEN}"

doc = {
    "_comment": (
        "Generated by tools/runtime-vectors/generate.py. A wire commitment "
        "between apps/server and apps/runtime (PLAN.md decision 77b); a "
        "changed vector is a protocol change."
    ),
    "host_key": {
        "seed_b64url": b64(HOST_SEED),
        "public_key_b64url": b64(HOST_PK),
    },
    "server_key": {
        "seed_b64url": b64(SERVER_SEED),
        "public_key_b64url": b64(SERVER_PK),
    },
    "enroll": {
        "server_id": SERVER_ID,
        "token": TOKEN,
        "token_id": TID,
        "message": EM.decode(),
        "signature_b64url": b64(ed.signature(EM, HOST_SEED, HOST_PK)),
    },
    "connect": {
        "server_id": SERVER_ID,
        "host_id": HOST_ID,
        "nonce": NONCE,
        "message": CM.decode(),
        "signature_b64url": b64(ed.signature(CM, HOST_SEED, HOST_PK)),
    },
    "enrollment_string": {
        "valid": [
            {
                "string": ENROLLMENT,
                "server_url": URL,
                "server_id": SERVER_ID,
                "server_pubkey_b64url": b64(SERVER_PK),
                "token": TOKEN,
            },
            {
                "string": f"{ENROLL_PREFIX}https://storm.example:443/base:{SERVER_ID}:{b64(SERVER_PK)}:{TOKEN}",
                "server_url": "https://storm.example:443/base",
                "server_id": SERVER_ID,
                "server_pubkey_b64url": b64(SERVER_PK),
                "token": TOKEN,
            },
        ],
        "invalid": [
            {"string": f"storm-enroll:v2:{URL}:{SERVER_ID}:{b64(SERVER_PK)}:{TOKEN}", "why": "unknown version"},
            {"string": f"{ENROLL_PREFIX}{SERVER_ID}:{b64(SERVER_PK)}:{TOKEN}", "why": "no server_url"},
            {"string": f"{ENROLL_PREFIX}ftp://x:{SERVER_ID}:{b64(SERVER_PK)}:{TOKEN}", "why": "not http(s)"},
            {"string": f"{ENROLL_PREFIX}{URL}:{SERVER_ID}:{b64(SERVER_PK)}=:{TOKEN}", "why": "padded key"},
            {"string": f"{ENROLL_PREFIX}{URL}:{SERVER_ID}:{b64(SERVER_PK)}:sen_nodot", "why": "token without a secret half"},
            {"string": f"{ENROLL_PREFIX}{URL}:srv bad:{b64(SERVER_PK)}:{TOKEN}", "why": "server_id charset"},
        ],
    },
}

out = ROOT / "docs" / "runtime-vectors.json"
out.write_text(json.dumps(doc, indent=2) + "\n")
print(f"wrote {out}")
